version: 0.2

env:
  variables:
    deployableUnit: webapp

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - ls -lha
      - pwd
      - npm config set registry http://app-n-loadb-ig2d2aaehljl-531754914.us-east-1.elb.amazonaws.com/repository/npm-group/
      - npm install
      - npm run build
      - zip dist.zip ./dist/*
      - ls -la
  post_build:
    commands:
      - echo "derp"
artifacts:
  base-directory: $CODEBUILD_SRC_DIR/${deployableUnit}/
  discard-paths: yes
  files:
    - buildspec-build-image.yaml
    - dist.zip
